import Head from 'next/head'
import { useRouter } from 'next/router'

import React from 'react'

import Footer from 'components/Footer'
import Header from 'components/Header'
import Layout from 'components/Layout'
import SearchResults from 'components/Results'

function Results() {
  const router = useRouter()

  console.log(router.query.id)
  return (
    <>
      <Head>
        <title>Resultados | Legislação Portuguesa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout>
        <SearchResults />
      </Layout>
      <Footer />
    </>
  )
}

export default Results
