import type { NextPage } from 'next'
import Head from 'next/head'

import SearchBar from 'components/SearchBar'

const Home: NextPage = () => (
  <>
    <Head>
      <title>Página Inicial | Legislação Portuguesa</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      Google
      <SearchBar />
      <button type="submit">Search</button>
      <button type="submit">I&apos;m feeling lucky</button>
    </main>
  </>
)

export default Home
