import type { NextPage } from 'next'
import Head from 'next/head'

import SearchBar from 'components/SearchBar'

const Home: NextPage = () => (
    <>
      <Head>
        <title>Página Inicial | Legislação Portuguesa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchBar/>
      </main>
    </>
  )

export default Home
