import { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'

import React, { useEffect } from 'react'

import Footer from 'components/Footer'
import Header from 'components/Header'
import Layout from 'components/Layout'
import SearchResults from 'components/Results'
import { useSearch } from 'context/search'

const Results: NextPage = () => {
  const { searchQuery, state } = useSearch()
  const router = useRouter()

  useEffect(() => {
    const { query } = router

    if (!router.query) return

    const { q } = query

    if (q !== undefined && state.count === 0) {
      searchQuery(q.toString(), 1)
    } else if (window.location.href.match(/\?q=/) === null) {
      searchQuery('', 1)
    }
  }, [router.query])

  return (
    <>
      <Head>
        <title>Resultados | Legislação Portuguesa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout>
        <SearchResults />
      </Layout>
      <Footer />
    </>
  )
}

export default Results
