@hostname = localhost
@port = 5002
@host = {{hostname}}:{{port}}
@contentType = application/json
@core = articles

###

# Search by articles containing "horas extraordinárias"
http://{{host}}/solr/{{core}}/select
content-type: {{contentType}}

{
    "params": {
        "defType": "edismax",
        "qf": "title_raw^3 title^2 text_raw^1.5 text^1 path^0.5 book^0.25",
        "bq": "state:Consolidado^4",
        "pf": "title_raw^3 title^2 text_raw^1.5 text^1 path^0.5 book^0.25",
    },
    "query": "horas extraordinárias",
}

###

# Search by articles containing "horas extraordinárias" in book "Código do Trabalho"
http://{{host}}/solr/{{core}}/select
content-type: {{contentType}}

{
    "params": {
        "defType": "edismax",
        "qf": "title_raw^3 title^2 text_raw^1.5 text^1 path^0.5",
        "bq": "state:Consolidado^4",
        "pf": "title_raw^3 title^2 text_raw^1.5 text^1 path^0.5",
    },
    "query": "horas extraordinárias +book:\"Código do Trabalho\"",
}

###

# Search "socialismo" from the initial constituicao text (1976)
http://{{host}}/solr/{{core}}/select
content-type: {{contentType}}

{
    "params": {
        "defType": "edismax",
        "qf": "title_raw^3 title^2 text_raw^1.5 text^1 path^0.5",
    }
    "query": "socialismo +date:[1976-01-01T00:00:00Z TO 1976-12-31T23:59:59Z] +book:constituicao",
}

###

# Search articles by a title containing "trabalhador"
http://{{host}}/solr/{{core}}/select
content-type: {{contentType}}

{
    "params": {
        "defType": "edismax",
        "bq": "state:Consolidado^4",
        "qf": "title_raw^1.5 title",
    }
    "query": "trabalhador",
}

###

# Same as above but not in book "Código do Trabalho"
http://{{host}}/solr/{{core}}/select
content-type: {{contentType}}

{
    "params": {
        "defType": "edismax",
        "bq": "state:Consolidado^4",
        "qf": "title_raw^1.5 title",
    }
    "query": "trabalhador -book:\"Código do Trabalho\"",
}

###

# Search the status of articles that contain "socialismo" or "classes" and check its status
http://{{host}}/solr/{{core}}/select
content-type: {{contentType}}

{
    "params": {
        "defType": "edismax",
        "bq": "state:Consolidado^4",
        "qf": "title_raw^3 title^2 text_raw^1.5 text^1",
    }
    "query": "socialismo",
}

###

# Search "residência habitual da criança nos termos do artigo 8 do regulamento bruxelas"

http://{{host}}/solr/{{core}}/select
content-type: {{contentType}}

{
    "params": {
        "defType": "edismax",
        "bq": "state:Consolidado^4",
        "qf": "key^4 title_raw^3 title^2 text_raw^1.5 text^1 book^0.5"
    }
    "query": "construcao do socialismo artigo 1 da constituicao",
}

###

# Search books that contain "pedido de indemnização civil"
http://{{host}}/solr/{{core}}/select
content-type: "application/json"

{
    "params": {
        "defType": "edismax",
        "qf": "title_raw^3 title^2 text_raw^1.5 text^1",
        "bq": "state:Consolidado^4",
        "fl": "book"
    },
    "query": "\"pedido de indemnização civil\"",
}
 
###

# Search articles that contain "buscas domiciliárias / crimes informáticos / acesso ilegítimo / falsidade informática" 
http://{{host}}/solr/{{core}}/select
content-type: "application/json"

{
    "params": {
        "defType": "edismax",
        "qf": "title_raw^3 title^2 text_raw^1.5 text^1",
        "bq": "state:Consolidado^4"
    },
    "query": "\"buscas domiciliárias\" \"crimes informáticos\" \"acesso ilegítimo\" \"falsidade informática\"",
}