@hostname = localhost
@port = 80
@host = {{hostname}}:{{port}}/api
@contentType = application/json

###

# General search
http://{{host}}/search
content-type: {{contentType}}

{
    "query": "horas extraordinárias"
}